- README.md
- mkdocs.yml
- src/changelogs/v2.19.0.md
- src/changelogs/v2.20.0.md
- src/index.md
- src/managing-workflow/upgrading-workflow.md
- src/quickstart/install-cli-tools.md
- src/roadmap/releases.md
- src/users/cli.md
Updating the docs and cli links for Hephy Workflow v2.20.0 release.
> docs(README.md): update docs for release v2.20.0

- src/troubleshooting/applications.md
I had this problem on GKE, so it might be useful to help others address this kind of problem too.
> docs(worflow): Improved app troubleshooting. How to connect to external services behind kubernetes

- src/managing-workflow/tuning-component-settings.md
https://docs.teamhephy.info/managing-workflow/tuning-component-settings/#grafana
> grafana table is broken

- README.md
- mkdocs.yml
- src/changelogs/v2.20.1.md
- src/index.md
Changelog for v2.20.1 added here.
> docs(changelogs): add new patch release v2.20.1

- README.md
- mkdocs.yml
- src/changelogs/v2.21.0.md
- src/index.md
Adding the new release Hephy Workflow v2.21.0
> New Release v2.21.0

- README.md
Fixing some broken links in the README because this the main repo for the project.
> docs(README): fix some broken links on the README

- src/managing-workflow/tuning-component-settings.md
Documents the environment variable introduced in https://github.com/teamhephy/controller/pull/112.
Signed-off-by: Johann Fuechsl <johann@fuechsl.co>
> Document `DEIS_IGNORE_SCHEDULING_FAILURE`

- src/applications/deploying-apps.md
ref: teamhephy/workflow#109
Document buildpack environment settings
> docs(apps): document buildpack env settings

- src/applications/managing-app-processes.md
Documentation for https://github.com/teamhephy/workflow-cli/pull/48 
Fixing https://github.com/teamhephy/workflow-cli/issues/5
> fix(build): remove auto Procfile lookup for deis pull

- README.md
- src/quickstart/install-cli-tools.md
- src/quickstart/provider/minikube/install-minikube.md
> docs(cli): fix to stable on cli instructions and date of v2.21.5

- README.md
- mkdocs.yml
- src/changelogs/v2.21.6.md
- src/index.md
- src/quickstart/install-cli-tools.md
> docs(changelogs): add new patch release v2.21.6

- README.md
- mkdocs.yml
- src/changelogs/v2.22.0.md
- src/index.md
- src/quickstart/install-cli-tools.md
New major release with support for k8s 1.16+  api changes. :fox_face: 
> docs(changelogs): add new major release v2.22.0

- charts/workflow/values.yaml
> chore(charts): add AZURE_STORAGE_CONNECTION_STRING to values.yaml

- README.md
- mkdocs.yml
- src/changelogs/v2.22.1.md
- src/index.md
- src/quickstart/install-cli-tools.md
> docs(changelogs): add new patch release v2.22.1

- README.md
- mkdocs.yml
- src/changelogs/v2.22.2.md
- src/index.md
- src/quickstart/install-cli-tools.md
> docs(changelogs): add new patch release v2.22.2

- mkdocs.yml
- src/_includes/dns.md
> chore(mkdocs): fixing mkdocs so it builds in strict mode

- README.md
- mkdocs.yml
- src/changelogs/v2.22.3.md
- src/index.md
- src/quickstart/install-cli-tools.md
> docs(changelogs): add new patch release v2.22.3

- README.md
Happy New Year Team Hephy! :champagne: :tada:  :pray: 
> docs(README): fix year 2021 for v2.22.3

- README.md
- mkdocs.yml
- src/changelogs/v2.23.0.md
- src/index.md
- src/quickstart/install-cli-tools.md
> docs(changelogs): add new release v2.23.0

- helmfile.lock
- helmfile.yaml
- adding helmfile example for workflow install
- `helmfile --debug -f helmfile.yaml apply`
> feat(helm): add helmfile example for workflow

- charts/workflow/values.yaml
- chore(charts): new controller ingress_class value 
- chore(charts): rm experimental from native_ingress
> Workflow chart updates v2.23.1

- src/managing-workflow/aws-eks-running-builds-on-fargate.md
Advanced guide for running slugbuilds on Fargate when using EKS. Happy to take feedback 😊
> docs(aws): slugbuild on fargate guide
